#!/usr/bin/env bash
set -eu

echo "🔵 build"
source hooks/.config

echo "✅ Will build the following architectures: $(IFS=, ; echo "${build_architectures[@]}")"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"

for arch in ${build_architectures[@]}; do
  echo "✅ building $arch"
  echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"

  OMBI_ARCH=${ombi_arch_map[${arch}]}
  # OMBI_RELEASE=$(curl -s https://api.github.com/repos/Ombi-app/Ombi/releases/latest | jq -r '.tag_name')
  OMBI_RELEASE=$(curl -s https://api.github.com/repos/Ombi-app/Ombi/releases | jq -r '.[0].tag_name')
  # OMBI_URL=$(curl -k -s https://api.github.com/repos/Ombi-app/Ombi/releases/tags/${OMBI_RELEASE} | jq -r '.assets[].browser_download_url' | grep linux-${OMBI_ARCH}.tar.gz)
  OMBI_URL=$(curl -k -s https://api.github.com/repos/Ombi-app/Ombi/releases/tags/${OMBI_RELEASE} | jq -r '.tarball_url')

  echo OMBI_URL = ${OMBI_URL}
  docker exec docker_daemon docker build \
    --squash \
    --platform=${docker_arch_map[${arch}]} \
    --build-arg BASE_IMAGE_PREFIX=${base_image_prefix_map[${arch}]} \
    --build-arg OMBI_RELEASE=${OMBI_RELEASE} \
    --build-arg OMBI_ARCH=${OMBI_ARCH} \
    --build-arg OMBI_URL=${OMBI_URL} \
    --file /build/${IMAGE_NAME_simple}/${DOCKERFILE_PATH} \
    --tag "${IMAGE_NAME}-${arch}"  \
    /build/${IMAGE_NAME_simple}
done

echo "✅ images built:"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
docker exec docker_daemon docker image ls

trap "exit 1"          HUP INT PIPE QUIT TERM
